[package]
name = "octree-experiment"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.1"
bevy_prototype_debug_lines = { version = "0.10.1", features = ["3d"] }
grid-tree = { git = "https://github.com/Lemonzyy/grid-tree-rs" }
rand = "0.8.5"
smooth-bevy-cameras = "0.8.0"
